catalog_product:
    resource:
        path: ../src/Catalog/Product/Presentation/Controller/
        namespace: App\Catalog\Product\Presentation\Controller
    type: attribute

openapi:
    resource: '@OpenApiBundle/config/routes.php'
