services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    # DDD

    Ddd\Domain\Event\NativeDomainEventPublisher: ~
    Ddd\Domain\Event\DomainEventPublisher: '@Ddd\Domain\Event\NativeDomainEventPublisher'
