services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Ddd\Infrastructure\Event\InMemoryDomainEventPublisher: ~

    Ddd\Domain\Event\DomainEventPublisher: '@Ddd\Infrastructure\Event\InMemoryDomainEventPublisher'
