services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Catalog\Product\Domain\Repository\ProductRepository:
        alias: App\Catalog\Product\Infrastructure\Persistence\Doctrine\OrmProductRepository

when@test:
    services:
        App\Catalog\Product\Domain\Repository\ProductRepository:
            alias: App\Catalog\Product\Infrastructure\Persistence\InMemory\InMemoryProductRepository
